### ISSUE TITLE
Make the HGVS parser as a separate package

### ISSUE THREAD

**Issue by ccwang002** [biocommons/hgvs#586] opened 2020-02-19 22:02 UTC
I was wondering if it's possible to release the HGVS parser as a separate package.

My use case is to read and parse a given variant's existing HGVSc and HGVSp annotation (from VEP etc). `hgvs.parser.Parser` nailed this problem by implementing a solid grammar, which is much better than hacking a regex-based solution. So my use case only requires the parser and doesn't really need to normalize or 'liftover' the HGVS strings. If my understanding is correct, `hgvs` only requires parsley and some biocommons' data structures to get the parser working. This will shrink down the total dependencies by quite a bit (such as SQL and database related packages). The advantage of keeping a smaller dependencies is that the downstream user requires less setup.

So I was wondering if it's possible to release hgvs modules individually. I don't know if the developers here are interested to make hgvs a bioconda package. If so, I am happy to help :)

Thanks for making this wonderful tool!

**Comment by reece** [comment] 2020-02-19 22:43
There's good separation of the parser and models from the algorithmic components, so splitting the package is possible and useful. However, it'd be a bit of work that I don't have time for.

I'll leave this open to track interest and perhaps future work. PRs welcomed!

**Comment by ccwang002** [comment] 2020-02-20 01:53
Sounds good! I will give it a try and if it works I will update here. Thanks again.

**Comment by reece** [comment] 2024-02-19 17:44
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.

**Comment by davmlaw** [comment] 2024-02-20 00:34
This is basically a dupe of #199 - requesting a reduction of dependencies

**Closed by davmlaw** 2024-02-20 00:34 UTC
Labels: resurrected
