### ISSUE TITLE
Support for Normalization of Intronic Variants 

### ISSUE THREAD

**Issue by Akeeeeshi** [biocommons/hgvs#463] opened 2017-09-18 15:43 UTC
Getting this warning when annotating an intronic variant in a region that requires shifting (i.e normalization). 

**WARNING:hgvs.assemblymapper:Normalization of intronic variants is not supported; returning unnormalized variant**

I read up on this topic from a issue posted from two years ago [here](https://github.com/biocommons/hgvs/issues/296). I was just curious if there are any updates on supporting intronic normalization.

**Comment by reece** [comment] 2017-09-21 14:50
Would you please send info to reproduce? At a minimum, that's a variant and the operation you were performing.

Transcripts don't contain intronic sequence, so it's impossible to normalize them.

What *should* be happening here is merely that you're getting a warning. I'll need the variant to make sure it's not something more serious.

**Comment by roys911** [comment] 2017-11-09 16:10
Hi Reece,
I am doing a validation study using hgvs package and encountering a similar problem with normalizing intronic variants using RefSeq transcripts. Example below

chr11 | 108218120 | CT | C | NM_000051.3 | ATM
Primary assembly is GRCh37
The hgvs output 
cdna : NM_000051.3:c.8671+29del
aa : <type 'exceptions.AttributeError'>

when I manually compute the hgvs for c. it should be c.8671+33del. This because of a homopolymer of 5Ts in that region. It is understandable that hgvs is not normalizing this because of the absence of the intronic sequence in Refseq transcripts. 
Is it possible that for intronic variants, the hgvs software can extract the intronic sequence from the correct reference sequence (primary assembly) and normalize the introinc variants?  Any temp workaround this?
Thanks!

**Comment by reece** [comment] 2017-11-25 06:28
The workaround is for you to project the variant to the genome, normalize there (with direction set appropriate for transcript strand), then project back to the transcript. This requires that the caller be explicit about which genomic reference to use for the implied intronic sequence.

We have no plans to implement this in hgvs, so I'm going to close this issue as won't fix.

**Closed by reece** 2017-11-25 06:28 UTC
