### ISSUE TITLE
Incorrect mapping of SNV to insertion on GRCh37

### ISSUE THREAD

**Issue by lacek** [biocommons/hgvs#508] opened 2018-07-26 10:47 UTC
Variant: [NM_001145026.1:c.715A>G](https://www.ncbi.nlm.nih.gov/clinvar/variation/156332)
hgvs version: 1.2.1
data_version: uta_20170629

In hgvs-shell, when mapped to genomic HGVS, the variant becomes an insertion:

```python
hgvs = 'NM_001145026.1:c.715A>G'
vc = hp.parse_hgvs_variant(hgvs)
vg = am37.c_to_g(vc)
print(vg)
# NC_000012.11:g.80860615_80860616insGAGAATAGTGAATCTTTTTTATGGAGTACAGCCAGCCCTTCTCCAACCCTTGGTGGAGTTACACCTCCATCGCGTACCACACATTCATCAAGCACGTTGACACAGAATGAGATCAGCTCTGTGTGGAAAGAGCCTATCAGTTTTGTAGTGACACACTTGAG
```

I suspect this is due to mismatch of the transcript NM_001145026.1 on GRCh37, but mapping a SNV to insertion does not sound right anyway.

More examples:

| Coding HGVS | HGVS mapped to GRCh37 |
|-|-|
| [NM_001145026.1:c.715A>G](https://www.ncbi.nlm.nih.gov/clinvar/variation/156332) | NC_000012.11:g.80860615_80860616insGAGAATAGTGAATCTTTTTTATGGAGTACAGCCAGCCCTTCTCCAACCCTTGGTGGAGTTACACCTCCATCGCGTACCACACATTCATCAAGCACGTTGACACAGAATGAGATCAGCTCTGTGTGGAAAGAGCCTATCAGTTTTGTAGTGACACACTTGAG |
| [NM_001145026.1:c.837T>A](https://www.ncbi.nlm.nih.gov/clinvar/variation/156333/) | NC_000012.11:g.80860626_80860627insCATAACTTTTTG |
| [NM_000828.4:c.-2G=](https://www.ncbi.nlm.nih.gov/clinvar/variation/167157/) | NC_000023.10:g.122318386_122318387insG |

**Comment by icebert** [comment] 2018-07-27 07:18
This is due to transcript-genome alignment gap. Taking `NM_001145026.1:c.837T>A` for example, the alignment context is:

```text
                         80860626    80860627
                            |            |
NC_000012.11      ACCTTATACAA------------AA
NM_001145026.1    ACCTTATACAACATATCTTTTTGAA
                                 ^
                                837
```

Supposing you sequenced this gene of a person and aligned his sequence to NM_001145026.1 and found the variant at 837T>A. Then if you align his sequence to genomic NC_000012.11, what variant will you get? It's `NC_000012.11:g.80860626_80860627insCATAACTTTTTG`, right?

The fundamental logic behind variant mapping is that the original variant and the mapped variant should refer to the same altered sequence. Only in this way the two variants are equal. The altered sequence constructed from `NM_001145026.1:c.837T>A` at transcript level and that constructed from `NC_000012.11:g.80860626_80860627insCATAACTTTTTG` at genomic level is the same. No other types of mapped variants could derive the same altered sequence. Thus, I think `NC_000012.11:g.80860626_80860627insCATAACTTTTTG` is the only reasonable mapped variant for `NM_001145026.1:c.837T>A` in this transcript-genome alignment gap.

These examples demonstrate the hgvs package considers alignment gaps and gives the correct mapped variants, which is an important distinct feature compared to other tools.

**Comment by lacek** [comment] 2018-07-27 08:55
You are right. After going through your detailed explanation, this really make sense to me now.

**Comment by lacek** [comment] 2018-07-27 10:55
I have further checked the variant `NM_001145026.1:c.837T>A` on dbSNP, and it reports the genomic HGVS as `NC_000012.11:g.80849348A>T` ([rs183258549](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=183258549)).

The sequence NC_000012.11:80849339-80849363 is `ACCTTATACAACATATCTTTTTGAA`, the same as that of NM_001145026.1 in your example. Why aren't we mapping the variant to this region? Is this somethong to do with UTA instead?

**Comment by PeteCausey-Freeman** [comment] 2018-07-27 11:19
Hi Wallace and Meng.,

For the record Wallace is correct. This particular transcript aligned to NC_000012.11 has a discrepancy between the alignments contained in UTA and the alignments from the official GFF3 files released by RefSeq.

# Chromosome range                                                    Mapped positions from RefSeq                  Mapped positions from UTA
Reference=NC_000012.11 80840806 80840843   Target=NM_001145026.1 420 452 +        UTA=NM_001145026.1 391-1 460+2
Reference=NC_000012.11 80849305 80849321   Target=NM_001145026.1 549 565 +        UTA=NM_001145026.1 461-1 660+1
Reference=NC_000012.11 80860616 80860628   Target=NM_001145026.1 822 834 +        UTA=NM_001145026.1 661-1 846
Reference=NC_000012.11 80862485 80862617   Target=NM_001145026.1 907 1039 +     UTA=NM_001145026.1 911 1039

In total, 4 exons are misaligned.

There are several transcripts in UTA which have similar issues. I can provide a list of the misaligned transcript/chromosome combinations if this would be helpful.

Cheers

Pete

**Comment by reece** [comment] 2018-08-05 15:47
I'm closing this ticket since the root cause is not related to the hgvs 
@lacek: Also see #392.

**Closed** 2018-08-05 15:48 UTC
