### ISSUE TITLE
How to get VCF position of HGVS

### ISSUE THREAD

**Issue by ralonso-igenomix** [biocommons/hgvs#441] opened 2017-05-24 09:06 UTC
Hello,

I have a doubt, I would like to get the vcf position of a cHGVS because I know they are the same regarding the effect in the transcript:
cHGVS="NM_000543.4:c.108_124del"
var_c1 = hp.parse_hgvs_variant(cHGVS)
cHGVS="NM_000543.4:c.126_143del"
var_c2 = hp.parse_hgvs_variant(cHGVS)

I see by these two pages that the Genomic coordinates (VCF) with respect to genome build GRCh37 is 11-6411935-TGCTGGCGCTGGCGCTGGC-T
https://variantvalidator.org/variantvalidation/?variant=NM_000543.4%3Ac.108_124del&primary_assembly=GRCh37&alignment=splign
https://variantvalidator.org/variantvalidation/?variant=NM_000543.4%3Ac.126_143del&primary_assembly=GRCh37&alignment=splign

Would you know if there is a way to get this programatically?

Or maybe, is there any way to get the consensus sequence applying to the hgvs?
Or also get the automapped transcript?
Thanks in advance!

**Comment by reece** [comment] 2017-05-24 14:44
This issue is essentially a duplicate of #243. I'll close this issue in favor of the original.

VCF⮂HGVS  would be useful functionality. No ETA at this time.

**Closed by reece** 2017-05-24 14:44 UTC
