### ISSUE TITLE
Duplications in the Last Position of the CDS are Throwing Errors

### ISSUE THREAD

**Issue by Akeeeeshi** [biocommons/hgvs#449] opened 2017-06-20 13:58 UTC
It appears that duplications in the last position of the CDS are causing "string index out of range"  errors when using the package. 

Example HGVS_g's causing this problem: "NC_000006.11:g.30558477_30558478insA" and "NC_000016.9:g.31770696_31770697insA"

Here is an example of the error being thrown:
<img width="864" alt="screen shot 2017-06-20 at 9 55 51 am" src="https://user-images.githubusercontent.com/28007814/27336838-c448774e-559e-11e7-97ca-466a959c3d8f.png">

Here is the snippet of code this error is derived from:

<img width="1364" alt="upload 1" src="https://user-images.githubusercontent.com/28007814/27336896-ec8bf7f8-559e-11e7-88be-3806c1783839.png">

Please advise.

**Comment by icebert** [comment] 2017-06-20 14:05
Hi Akeeeeshi, thank you for pointing this. We also noticed this issue and fixed it in a recent pull request. It will be merged soon after review.

**Comment by reece** [comment] 2017-06-23 08:46
@Akeeeeshi : Thanks for the report. I couldn't reproduce your bug, but Meng thinks he may have fixed it. Please try again.

In the future, it helps a lot to have bug reports that include a minimal series of commands to reproduce the error rather than the backtrace. Here's an ideal example (it doesn't reproduce the bug, but gives an idea of what helps.)


```
(venv) snafu$ hgvs-shell
In [1]: v = hp.parse_hgvs_variant("NC_000006.11:g.30558477_30558478insA")

In [2]: am37.g_to_c(v, 'NM_001025091.1')
Out[2]: SequenceVariant(ac=NM_001025091.1, type=c, posedit=2538dup)
```

You don't have to use `hgvs-shell` (which is installed whenever you install hgvs), but doing so means that we can copy-paste exactly what generated the error for you.

Thanks for your reports!

**Comment by reece** [comment] 2017-06-23 08:49
P.S. I haven't pushed a new release yet. If you're not familiar with installing from source, please wait for the next release (ETA: a few days).

**Closed** 2017-06-23 08:48 UTC

**Comment by Akeeeeshi** [comment] 2017-07-07 15:26
@reece Any idea when the next release will be?

**Comment by reece** [comment] 2017-07-12 20:16
@Akeeeeshi: Please see the mailing list for release info if you haven't already.
